package Tests;
//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RegisterTest {
	private String
	exePath =
	"C:\\Users\\chromedriver.exe";
private WebDriver driver;
private Map<String, Object> vars;
JavascriptExecutor js;
@Before
public void setUp() {
System.setProperty("webdriver.chrome.driver", exePath);
 driver = new ChromeDriver();
 js = (JavascriptExecutor) driver;
 vars = new HashMap<String, Object>();
}
@After
public void tearDown() {
 driver.quit();
}
@Test
public void register() {
 driver.get("https://www.sportivo.rs/");
 driver.manage().window().setSize(new Dimension(1296, 688));
 driver.findElements(By.className("cookieinfo-close")).get(0).click();
 driver.findElement(By.id("btl-panel-registration")).click();
 driver.findElement(By.id("btl-input-name")).sendKeys("Miloš");
 driver.findElement(By.id("btl-input-username1")).click();
 driver.findElement(By.id("btl-input-username1")).sendKeys("milos1998");
 driver.findElement(By.id("btl-input-password1")).click();
 driver.findElement(By.id("btl-input-password1")).sendKeys("milos.998");
 driver.findElement(By.id("btl-input-password2")).click();
 driver.findElement(By.id("btl-input-password2")).sendKeys("milos.998");
 driver.findElement(By.id("btl-input-email1")).click();
 driver.findElement(By.id("btl-input-email1")).sendKeys("milosmaric@gmail.com");
 driver.findElement(By.id("btl-input-email2")).click();
 driver.findElement(By.id("btl-input-email2")).sendKeys("milosmaric@gmail.com");
 driver.switchTo().frame(1);
 driver.switchTo().defaultContent();
 driver.findElement(By.cssSelector(".btl-buttonsubmit:nth-child(21) > .btl-buttonsubmit")).click();
 /*
 assertTrue(driver.getPageSource().contains("Hvala na vašoj registraciji."));
 Assert bi trebao da izlgeda ovako, ali zbog robota na koji je nemoguće kliknuti je zakomentarisan.
 */
}
}

