package Tests;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchTest {
	private String
	exePath =
	"C:\\Users\\chromedriver.exe";
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	  System.setProperty("webdriver.chrome.driver", exePath);
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void search() {
    driver.get("https://www.sportivo.rs/");
    driver.manage().window().setSize(new Dimension(1296, 688));
    driver.findElement(By.id("q_164_0")).click();
    driver.findElement(By.id("q_164_0")).sendKeys("patike");
    driver.findElement(By.id("q_164_0")).sendKeys(Keys.ENTER);
    assertTrue(driver.findElement(By.className("naziv-proizvoda")).getText().contains("PATIKE"));
    try {
		Thread.sleep(1500);
	} catch (InterruptedException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
    driver.get("https://www.sportivo.rs/");
    driver.manage().window().setSize(new Dimension(1296, 688));
    driver.findElement(By.id("q_164_0")).click();
    driver.findElement(By.id("q_164_0")).sendKeys("368845-02");
    driver.findElement(By.id("q_164_0")).sendKeys(Keys.ENTER);
    assertTrue(driver.getPageSource().contains("368845-02"));
  }
}
